name: Aula 2 Exercicio 2

on:
  push:

jobs:
  checkout_code:
    name: Faz check out do codigo
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{vars.VALOR_UPLOAD}}
        path: .
